projetofinal/clube/urls.py
from django.urls import path
from . import views

app_name = 'clube'

urlpatterns = [
    path('', views.home, name='home'),

    path('registar', views.registar, name='registar'),
    path('atleta', views.registar_atleta, name='registar_atleta'),
    path('treinador', views.registar_treinador, name='registar_treinador'),


    path('historia/', views.historia, name='historia'),

    path('jogos/', views.jogos, name='jogos'),
    path('criar_jogo/', views.criar_jogo, name='criar_jogo'),
    path('<int:jogo_id>/', views.detalhe_jogo, name='detalhe_jogo'),

    path('treinos/', views.treinos, name='treinos'),
    path('criar_treino/', views.criar_treino, name='criar_treino'),
    path('<int:treino_id>/', views.detalhe_treino, name='detalhe_treino'),

    path('fazerlogin', views.fazerlogin, name='fazerlogin'),
    path('fazerlogout', views.fazerlogout, name='fazerlogout'),

    path('users/', views.lista_users, name='lista_users'),

]

projetofinal/projetofinal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('clube/', include('clube.urls')),
    path('admin/', admin.site.urls),
]

projetofinal/clube/models.py
from datetime import timezone, datetime
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User

class Utilizador(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    equipa = models.CharField(max_length=50)
    num_tel = models.IntegerField(unique=True)
    data_nascimento = models.DateField()
    sexo = models.CharField(max_length=10)
class Atleta(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    equipa = models.CharField(max_length=50)
    num_tel = models.IntegerField(unique=True)
    data_nascimento = models.DateField()
    sexo = models.CharField(max_length=10)

    def __str__(self):
        return self.user.username

class Treinador(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    equipa = models.CharField(max_length=50)
    num_tel = models.IntegerField(unique=True)


class Treino(models.Model):
    treino_data = models.DateField(default=False)
    treino_hora = models.TimeField(default=False)
    treino_local = models.CharField(max_length=200)

class Opcao_treino(models.Model):
    treino = models.ForeignKey(Treino, on_delete=models.CASCADE)
    opcao_treino = models.CharField(max_length=20)
    presencas = models.IntegerField(default=0)

class Voto_treino(models.Model):
    jogador = models.ForeignKey(User, on_delete=models.CASCADE)
    treino = models.ForeignKey(Treino, on_delete=models.CASCADE, null=True)
    justificacao = models.CharField(max_length=200, blank=True)
    vai_treinar = models.BooleanField(default=True)

class Jogo(models.Model):
    jogo_data = models.DateField('data')
    jogo_hora = models.TimeField()
    jogo_local = models.CharField(max_length=200)

class Opcao_jogo(models.Model):
    jogo = models.ForeignKey(Jogo, on_delete=models.CASCADE)
    opcao_jogo = models.CharField(max_length=20)
    presencas = models.IntegerField(default=0)

projetofinal/clube/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User, Atleta, Jogo, Treino, Voto_treino


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + ('email',)


class AtletaForm(forms.ModelForm):
    equipa = forms.ChoiceField(choices=[('Infantis M', 'Infantis M'), ('Infantis F', 'Infantis F'),
                                        ('Iniciados M', 'Iniciados M'), ('Iniciadas F', 'Iniciadas F'),
                                        ('Cadetes M', 'Cadetes M'), ('Cadetes F', 'Cadetes F'),
                                        ('Juvenis M', 'Juvenis M'), ('Juvenis F', 'Juvenis F'),
                                        ('Juniores M', 'Juniores M'), ('Juniores F', 'Juniores F')], required=True)
    num_tel = forms.IntegerField(required=True)
    data_nascimento = forms.DateField(required=True, widget=forms.TextInput(attrs={'type': 'date'}))
    sexo = forms.ChoiceField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], required=True)

    class Meta:
        model = Atleta
        fields = ['equipa', 'num_tel', 'data_nascimento', 'sexo']

class TreinadorForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    equipa = forms.ChoiceField(choices=[('M', 'Infantis M'), ('F', 'Infantis F'), ('M', 'Iniciados M'),
                                        ('F', 'Iniciadas F'), ('M', 'Cadetes M'), ('F', 'Cadetes F'),
                                        ('M', 'Juvenis M'), ('F', 'Juvenis F'),
                                        ('M', 'Juniores M'), ('F', 'Juniores F')], required=True)
    num_tele = forms.CharField(max_length=20, required=True)
    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + ('email', 'equipa', 'num_tele')

class JogoForm(forms.ModelForm):
    class Meta:
        model = Jogo
        fields = ['jogo_local', 'jogo_data', 'jogo_hora']
        widgets = {
            'jogo_data': forms.DateInput(attrs={'type': 'date'}),
            'jogo_hora': forms.TimeInput(attrs={'type': 'time'}),
        }

class TreinoForm(forms.ModelForm):
    class Meta:
        model = Treino
        fields = ['treino_local', 'treino_data', 'treino_hora']
        widgets = {
            'treino_data': forms.DateInput(attrs={'type': 'date'}),
            'treino_hora': forms.TimeInput(attrs={'type': 'time'}),
        }

class VotoTreinoForm(forms.ModelForm):
    class Meta:
        model = Voto_treino
        fields = ['vai_treinar', 'justificacao']
        labels = {
            'vai_treinar': 'Disponível para o treino?',
            'justificacao': 'Justificação (caso não disponível)',
        }

projetofinal/clube/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User

from .forms import CustomUserCreationForm, AtletaForm, TreinadorForm, JogoForm, TreinoForm, VotoTreinoForm
from django.core.checks import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.template import context
from django.urls import reverse
from .models import Atleta, Jogo, Treino, Voto_treino, Opcao_treino


def home(request):
    context = {}
    return render(request, 'clube/home.html', context)

def is_admin(user):
    return user.is_authenticated and user.is_superuser

def fazerlogin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('clube:home')
        else:
            context = {'msg_erro': 'Credenciais inválidas'}
            return render(request, 'clube/fazerlogin.html', context)
    else:
        return render(request, 'clube/fazerlogin.html')


@login_required
def fazerlogout(request):
    logout(request)
    return HttpResponseRedirect(reverse('clube:home'))

def registar(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('clube:home')
    else:
        form = CustomUserCreationForm()
    return render(request, 'clube/registar.html', {'form': form})

def registar_atleta(request):
    if request.method == 'POST':
        user_form = CustomUserCreationForm(request.POST)
        atleta_form = AtletaForm(request.POST)
        if user_form.is_valid() and atleta_form.is_valid():
            user = user_form.save(commit=False)
            user.email = user_form.cleaned_data['email']
            user.save()
            atleta = atleta_form.save(commit=False)
            atleta.user = user
            atleta.save()
            return redirect('sucesso')
    else:
        user_form = CustomUserCreationForm()
        atleta_form = AtletaForm()
    return render(request, 'clube/registar_atleta.html', {'user_form': user_form, 'atleta_form': atleta_form})



def registar_treinador(request):
    if request.method == 'POST':
        form = TreinadorForm(request.POST)
        if form.is_valid():
            treinador = form.save()
            login(request, treinador)
            return redirect('clube:home')
    else:
        form = TreinadorForm()
    return render(request, 'clube/registar_treinador.html', {'form': form})

def historia(request):
    return render(request, 'clube/historia.html')

@login_required
def criar_jogo(request):
    if request.method == 'POST':
        form = JogoForm(request.POST)
        if form.is_valid():
            jogo = form.save(commit=False)
            jogo.criador = request.user
            jogo.save()
            form.save_m2m()
            return redirect('clube:home')
    else:
        form = JogoForm()
    return render(request, 'clube/criar_jogo.html', {'form': form})

@login_required
def jogos(request):
    jogos_criados = Jogo.objects.filter()
    context = {'jogos_criados': jogos_criados}
    return render(request, 'clube/home.html', context)

@login_required
def detalhe_jogo(request, jogo_id):
    jogo = get_object_or_404(Jogo, id=jogo_id)
    context = {'jogo': jogo}
    return render(request, 'clube/detalhe_jogo.html', context)

@login_required
def treinos(request):
    treinos_criados = Treino.objects.filter()
    context = {'treinos_criados': treinos_criados}
    return render(request, 'clube/home.html', context)


@login_required
def voto_treino(request, id_treino):
    treino = get_object_or_404(Treino, id=id_treino)

    if not treino.is_ativo:
        messages.warning(request, 'Esse treino não está mais ativo.')
        return redirect('clube:treinos')

    participando = Voto_treino.objects.filter(treino=treino, jogador=request.user).exists()

    if request.method == 'POST':
        form = VotoTreinoForm(request.POST)
        if form.is_valid():
            vai_treinar = form.cleaned_data['vai_treinar']
            justificacao = form.cleaned_data['justificacao']
            if not participando:
                voto = Voto_treino(treino=treino, jogador=request.user, vai_treinar=vai_treinar, justificacao=justificacao)
                voto.save()
                messages.success(request, 'Voto registrado com sucesso.')
            else:
                messages.warning(request, 'Você já votou neste treino.')
            return redirect('clube:detalhe_treino', treino_id=id_treino)
        else:
            messages.error(request, 'O formulário contém erros. Verifique os campos abaixo.')
    else:
        form = VotoTreinoForm()

    return render(request, 'clube/_treino.html', {'treino': treino, 'participando': participando, 'form': form})


@login_required
def detalhe_treino(request, treino_id):
    treino = get_object_or_404(Treino, id=treino_id)
    opcoes_treino = Opcao_treino.objects.filter(treino_id=treino.id)
    participando = Voto_treino.objects.filter(jogador=request.user, treino=treino).exists()
    context = {'treino': treino, 'opcoes_treino': opcoes_treino, 'participando': participando}
    return render(request, 'clube/detalhe_treino.html', context)

@login_required(login_url='fazerlogin')
def criar_treino(request):
    if hasattr(request.user, 'treinador'):
        if request.method == 'POST':
            form = TreinoForm(request.POST)
            if form.is_valid():
                treino = form.save(commit=False)
                treino.criador = request.user
                treino.save()
                form.save_m2m()
                return redirect('clube:home')
        else:
            form = TreinoForm()
        return render(request, 'clube/criar_treino.html', {'form': form})
    else:
        redirect('clube:login')



@login_required
def lista_users(request):
    users = User.objects.all()
    return render(request, 'clube/lista_users.html', {'users': users})

projetofinal/clube/templates/clube/apagar_user.html
{% block content %}

<h1>Excluir usuário {{ user.username }}</h1>
<p>Tem certeza que deseja excluir o usuário "{{ user.username }}"?</p>
<form method="POST">
  {% csrf_token %}
  <button type="submit">Excluir</button>
  <a href="{% url 'clube:lista_users' %}">Listar todos os atletas</a>
</form>
{% endblock %}

projetofinal/clube/templates/clube/criar_jogo.html
{% extends 'clube/home.html' %}
{% block titulo %}Criar Jogo{% endblock %}
{% block conteudo %}
  <h2>Criar jogo</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
  </form>
{% endblock %}

projetofinal/clube/templates/clube/criar_treino.html
{% extends 'clube/home.html' %}
{% block titulo %}Criar Treino{% endblock %}
{% block conteudo %}
  <h2>Criar Treino</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
  </form>
{% endblock %}

projetofinal/clube/templates/clube/detalhe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detalhes do Jogo</title>
</head>
<body>
    <h1>{{ jogo.jogo_data }} {{ jogo.jogo_hora }} - {{ jogo.jogo_local }}</h1>
    <p>Jogadores:</p>
    <ul>
        {% for jogador in jogo.jogadores.all %}
            <li>{{ jogador.username }}</li>
        {% endfor %}
    </ul>
</body>
</html>

projetofinal/clube/templates/clube/detalhe_jogo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detalhes do Treino</title>
</head>

<body>
    <h1>{{ treino.treino_data }} {{ treino.treino_hora }} - {{ treino.treino_local }}</h1>
    <p>Jogadores:</p>
    <ul>
        {% for jogador in treino.jogadores.all %}
            <li>{{ jogador.username }}</li>
        {% endfor %}
    </ul>

    <p>Opções de Treino:</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Votar</button>
    </form>

    <ul>
        {% for opcao_treino in treino.opcao_treino_set.all %}
            <li>{{ opcao_treino.opcao_treino }} - {{ opcao_treino.presencas }} presenças</li>
        {% endfor %}
    </ul>

</body>
</html>

projetofinal/clube/templates/clube/detalhe_treino.html
{% block content %}
  <h1>{{ treino.treino_local }}</h1>
  <p>Data: {{ treino.treino_data|date:'d/m/Y' }}</p>
  <p>Hora: {{ treino.treino_hora|time:'H:i' }}</p>

  {% if not treino.is_ativo %}
    <p>Esse treino não está mais ativo.</p>
  {% else %}
    {% if participando %}
      <p>Você já votou neste treino.</p>
    {% else %}
      <form method="POST" action="{% url 'clube:voto_treino' treino.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar voto</button>
      </form>
    {% endif %}
  {% endif %}

  <h2>Opções para o treino:</h2>
  <ul>
    {% for opcao in opcoes_treino %}
      <li>{{ opcao.texto_opcao }}</li>
    {% empty %}
      <li>Não há opções disponíveis para este treino.</li>
    {% endfor %}
  </ul>


    {% if request.user.atleta %}
    {% endif %}
{% endblock %}

projetofinal/clube/templates/clube/fazerlogin.html
{% extends 'clube/home.html' %}
{% block titulo %}Login{% endblock %}
{% block conteudo %}
    <body>
        {% if msg_erro %}
            <h2>{{ msg_erro }}</h2>
        {% endif %}

        <h1>Login:</h1>
        <form action="{% url 'clube:fazerlogin' %}" method="post">
            {% csrf_token %}
            <p>Username: </p>
            <input type="text" name="username" autofocus>
            <p>Password: </p>
            <input type="password" name="password">
            <br>
            <input type="submit" value="Log in">
        </form>
    </body>
{% endblock %}

projetofinal/clube/templates/clube/historia.html
{% extends 'clube/home.html' %}
{% block titulo %}História do Clube{% endblock %}

{% block conteudo %}
<body>
<div id="hist">
    <p> A 5 de Junho de 1950 lavrou-se a escritura do nascimento do CNG. E como surgiu esta designação? O nome não foi
        pacífico. Foram necessárias várias reuniões e filtrar os nomes propostos, alguns bem deslocados ou talvez não.
        Até o
        nome de “Adamastor” foi sugerido. De qualquer modo foi votado o de “Clube Nacional de Ginástica”, ideia feliz e
        cuja
        autoria foi de Guilherme Guedes, futuro primeiro Presidente da Direção e pessoa muito ligada a atividades
        desportivas, sobretudo no campo da Ginástica. Em simultâneo foi desenhado o emblema do Clube, símbolo que
        mereceu o
        maior cuidado e cuja paternidade pertenceu a Nuno de Barros, a Manuel dos Santos Franco e a João Abreu, pessoas
        a
        quem o Clube muito veio a dever no campo desportivo, competitivo e administrativo. Depois foi o normal nestas
        circunstâncias: a procura de uma Sede condigna, onde se pudesse ter um recanto de leitura, uma sala de reuniões,
        um
        local onde fosse possível jogar um bridge e, sobretudo, um espaço para a prática desportiva que, desde o
        primeiro
        momento seriam o Voleibol e a Ginástica, independentemente de outras que viessem a captar interessados, como o
        Ténis
        e o popular “Pingue-pongue”. Esse local foi encontrado e veio a situar-se na Av. Da República, na Vila Moita,
        tendo-se mantido como Sede desde a fundação, até ao ano de 1997.
        Simultaneamente houve que elaborar estatutos, definir as cores dos equipamentos desportivos, enfim, de pôr em
        marcha
        toda uma estrutura minimamente consistente. Claro que houve problemas, discussões e zangas, abandonos, mas o
        Clube
        resistiu porque o sonho comanda a vida, como diz o Poeta e porque houve pessoas determinadas, prontas a
        sacrificar-se para que o seu ideal triunfasse. Seria justo mencionar algumas, mas o receio de ser injusto com
        outras
        leva-nos a preferir elaborar uma lista, o mais completa que nos foi possível, crê-se mesmo que sem falhas
        significativas, de todos aqueles que passara ao longo dos anos pelos Órgãos Sociais do Clube e que, dentro das
        suas
        possibilidades, o consolidaram, vitalizaram e o transformaram de um pequeno Grupo, num Clube de razoável
        dimensão,
        com objetivos bem definidos, vivendo para a prática do desporto, virado com especial relance para a formação de
        jovens.
        Por outro lado, foi considerada como importante a existência de uma componente cultural. O objetivo seria, e é,
        a
        formação e captação dos espíritos mais sensíveis, o que, é justo dizê-lo, não tem sido fácil. O facto de recusar
        a
        prática do futebol, e antes enveredar por modalidades à data da sua fundação pouco desenvolvidas, fez nascer uma
        certa noção de elitismo. Hoje dir-se-á, e com razão, que há cinquenta anos, o Grupo Fundador do C.N.G. estava
        avançado em relação ao seu tempo. Existirão muitas modalidades tão espetaculares como o Vólei? A Ginástica não é
        considerada a modalidade mãe de todas as outras? E não são o Ténis de Mesa, a Natação, o Ténis, as diversas
        disciplinas de Artes Marciais, o Futebol de Salão e outras, nos nossos dias, acessíveis a todos e de gosto bem
        popular? E a cultura, nas suas diversas vertentes, sejam leitura, cinema, exposições, jogos de xadrez ou bridge,
        não
        deve ser promovida, de modo a beneficiar todos?
        O C.N.G. respeitou sempre as coletividades mais antigas, mas obteve o seu próprio espaço na Parede, sem ferir
        suscetibilidades e sem atropelar ninguém.
        O desenvolvimento do C.N.G. foi, como era natural, lento, difícil, por vezes penoso, com dificuldades
        financeiras
        imensas; por vezes foi necessária a boa vontade dos sócios mais abonados para satisfação de compromissos
        inadiáveis.
        Mas tudo foi vencido com determinação, com autoridade democrática e grande dedicação ao Clube. Todas as crises
        foram
        suplantadas, mesmo a que se abateu em 1974/1975, período em que o C.N.G. se transformou em sede de grandes
        debates
        políticos que originaram cisões graves, rompimentos tempestuosos e que só o tempo terá feito esquecer em parte.
        A
        vivência desse tempo dentro o Clube foi, afinal o reflexo da sociedade portuguesa da época e, embora tivessem
        ficado
        feridas, é firme convicção de que, se foram excedidos alguns limites eles foram posteriormente eliminados e
        considerados como próprios de um longo período de abafamento de expressão. Hoje o Clube vive em perfeita
        normalidade
        democrática, aliás como toda a sociedade portuguesa. O nosso Clube é um perfeito reflexo de um Portugal com
        desigualdades e com injustiças, é verdade, mas cheio de generosidade, de amplas liberdades, com uma juventude
        cheia
        de potencialidades onde o impossível não tem cabimento. Deixem-nos sonhar e afirmar que uma muito pequenas
        parcela
        da formação desta juventude cheia de potencialidades onde o impossível não tem cabimento. Deixem-nos sonhar e
        afirmar que uma muito pequena parcela da formação desta juventude viva pertence ao C.N.G e, por arrastamento, a
        todos aqueles que, em 1950, o fundaram.
        Muito se ficou a dever nos primeiros tempos ao Presidente Estevão Carrasco, pelo vigor ue soube imprimir à nova
        coletividade e, mais tarde, ao Presidente Branco Martins que dedicando-se, de alma e coração, ao Clube e aliando
        uma
        postura de autoridade e honestidade com uma formação humanista, conduziu o C.N.G. a uma posição de relevo na
        comunidade da Parede.
        Logo após a crise, em muitos sentidos libertadora, de 1974/1975, o C.N.G. recomeçou as suas atividades com
        grande
        empenho, mas demasiado fragilizado tanto no aspeto financeiro, como humano. Foram necessários vários anos para
        retomar a sua proverbial vitalidade, a qual terá sido alcançada sob a presidência de Júlio Correia.
        Entretanto o Clube, devido ao esforço e dedicação do sócio fundador Júlio Botelho Moniz, obteve a permissão para
        primeiro utilizar e depois possuir as instalações do Rádio Clube Português. Este facto proporcionou ao C.N.G. a
        posse de um excelente espaço para as práticas desportivas e de lazer, espaço este que tem sido constantemente
        melhorado, em boa parte devido à gestão de diversas Direções, sempre presididas por Manuel Madeira, outro sócio
        a
        quem o Clube muito fica a dever.
    <p>
</div>

</body>
{% endblock %}

projetofinal/clube/templates/clube/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <script type="text/javascript" src="{% static 'clube/js/javascript.js' %}"></script>
    <meta charset="UTF-8">
    <!--<meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
-->
    <title>
        {% block titulo %}
            Clube Nacional de Ginástica
        {% endblock %}
    </title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'clube/css/estilo.css' %}">
</head>


<body>
<header>
    <div class="container">
        <div class="user-info">
            <h1>Bem vindo ao Clube Nacional de Ginástica {{ user.username }}!!</h1>
        </div>
    </div>
</header>
<nav>
    <ul class="nav">
        <li class="nav-left"><a href="{% url 'clube:home' %}">Home</a></li>
        {% if request.user.is_authenticated %}
            <li class="nav-left"><a href="{% url 'clube:historia' %}">História do clube</a></li>
            <li class="nav-left"><a href="{% url 'clube:jogos' %}">Jogos</a></li>
            <li class="nav-left"><a href="{% url 'clube:treinos' %}">Treinos</a></li>
            {% if request.user.treinador %}
                <li class="nav-left"><a href="{% url 'clube:criar_treino' %}">Criar Treinos</a></li>
                <li class="nav-left"><a href="{% url 'clube:criar_jogo' %}">Criar Jogos</a></li>
            {% endif %}
            <li class="nav-right"><a href="{% url 'clube:lista_users' %}">Gerir Users</a></li>
            <li class="nav-right"><a href="{% url 'clube:home' %}">Perfil</a></li>
            <li class="nav-right"><a href="{% url 'clube:fazerlogout' %}">Logout</a></li>
        {% else %}
            <li class="nav-left"><a href="{% url 'clube:historia' %}">História do clube</a></li>
            <li class="nav-right"><a href="{% url 'clube:fazerlogin' %}">Login</a></li>
            <div class="dropdown">
                <li class="nav-right"><a href="{% url 'clube:registar' %}" class="dropa">Registar <i
                        class="fa fa-caret-down"></i></a></li>
                <div class="dropdown-content">
                    <a href="{% url 'clube:registar_atleta' %}">Atletas</a>
                    {% if request.user.is_superuser %}
                        <a href="{% url 'clube:registar_treinador' %}">Treinadores</a>
                        <a href="{% url 'clube:registar_diretor' %}">Diretor</a>
                    {% endif %}
                </div>
            </div>

        {% endif %}
    </ul>
</nav>

    {% block conteudo %}
        {% if request.user.is_authenticated %}
            <h2>{{ request.user.username }} está online</h2>
        {% else %}
            <h2>Não está conectado...</h2>
        {% endif %}
    {% endblock %}


{% if jogos_criados %}
    <h2>Jogos criados por {{ request.user.username }}:</h2>
    <ul>
        {% for jogo in jogos_criados %}
            <li>
                <a href="{% url 'clube:detalhe_jogo' jogo.id %}">{{ jogo.jogo_data }} {{ jogo.jogo_hora }} - {{ jogo.jogo_local }}</a>
            </li>
        {% endfor %}
    </ul>
{% endif %}


{% if treinos_criados %}
    <h2>Treinos criados por {{ request.user.username }}:</h2>
    <ul>
        {% for treino in treinos_criados %}
            <li>
                <a href="{% url 'clube:detalhe_jogo' treino.id %}">{{ treino.treino_data }} {{ treino.treino_hora }} - {{ treino.treino_local }}</a>
            </li>
        {% endfor %}
    </ul>
{% endif %}


</body>

<footer>
    <div id=""><h3><a href="{% url 'clube:home' %}">Contactos</a></h3></div>
</footer>
</html>

projetofinal/clube/templates/clube/registar.html
{% extends 'clube/home.html' %}
{% block titulo %}Registar{% endblock %}

{% block conteudo %}

    <h2>Página de Registo
        <li class="nav-right"><a href="{% url 'clube:registar_atleta' %}">Registar como atleta</a></li>
        <li class="nav-right"><a href="{% url 'clube:registar_treinador' %}">Registar como treinador</a></li>
        <li class="nav-right"><a href="{% url 'clube:registar_diretor' %}">Registar como diretor</a></li>
    </h2>
    <li><a href="{% url 'clube:home' %}">Home</a></li>
{% endblock %}

projetofinal/clube/templates/clube/registar_atleta.html
{% extends 'clube/home.html' %}
{% block titulo %}Atletas{% endblock %}


{% block conteudo %}
<h2>Página de Registo de Atleta</h2>
    <form method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ atleta_form.as_p }}
        <button type="submit">Registar Atleta</button>
    </form>

    <li><a href="{% url 'clube:home' %}">Home</a></li>
{% endblock %}